name: Nightly QA

on:
  schedule:
    - cron: '0 6 * * 0'    # 06:00 UTC every Sunday
  workflow_dispatch:              # manual run button

jobs:
  qa:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - uses: actions/checkout@v4

      # 2. Node + deps
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci

      # 3. Download Playwright’s Chromium (no install-deps)
      - name: Download Playwright Chromium
        run: npx playwright install chromium

      # 4. Crawl, analyse, build dashboard
      - run: node src/crawl.js
      - run: node src/checks.js
      - run: node src/report-ui/build.js

      # 5. Publish to GitHub Pages
      - name: Publish report
        uses: peaceiris/actions-gh-pages@v4
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
